import {
  MethodPayment,
  PaymentStatus,
  DeliveryStatus,
  OrderTransaction,
} from 'types/api';

export const MOCK_ORDER_TRANSACTIONS: OrderTransaction[] = [
  {
    orderTransactionId: 1,
    extraAmount: 100,
    description: 'Compra de productos electrónicos',
    productId: 101,
    productName: 'Laptop Lenovo ThinkPad',
    itemCount: 2,
    methodPayment: MethodPayment.CREDIT_CARD,
    invoiceNumber: 'INV-0001',
    client: 'Carlos López',
    amountPaid: 1800,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 700,
    sellingPrice: 900,
    profit: 400,
    operationDate: '2025-09-10',
    registerInSales: false,
  },
  {
    orderTransactionId: 2,
    extraAmount: 0,
    description: 'Pago parcial por accesorios',
    productId: 102,
    productName: 'Mouse inalámbrico Logitech',
    itemCount: 5,
    methodPayment: MethodPayment.CASH,
    invoiceNumber: 'INV-0002',
    client: 'Ana Torres',
    amountPaid: 250,
    paymentStatus: PaymentStatus.INCOMPLETE,
    deliveryStatus: DeliveryStatus.PENDING,
    purchasePrice: 30,
    sellingPrice: 50,
    profit: 100,
    operationDate: '2025-09-12',
    registerInSales: true,
  },
  {
    orderTransactionId: 3,
    extraAmount: 50,
    description: 'Venta con descuento especial',
    productId: 103,
    productName: 'Teclado Mecánico Redragon',
    itemCount: 1,
    methodPayment: MethodPayment.PAYPAL,
    invoiceNumber: 'INV-0003',
    client: 'Miguel Herrera',
    amountPaid: 500,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.IN_TRANSIT,
    purchasePrice: 200,
    sellingPrice: 500,
    profit: 300,
    operationDate: '2025-09-15',
    registerInSales: true,
  },
  {
    orderTransactionId: 4,
    extraAmount: 0,
    description: 'Compra cancelada',
    productId: 104,
    productName: 'Monitor Samsung 24"',
    itemCount: 1,
    methodPayment: MethodPayment.BANK_TRANSFER,
    invoiceNumber: 'INV-0004',
    client: 'Laura Mendoza',
    amountPaid: 0,
    paymentStatus: PaymentStatus.PENDING,
    deliveryStatus: DeliveryStatus.CANCELLED,
    purchasePrice: 120,
    sellingPrice: 250,
    profit: 0,
    operationDate: '2025-09-16',
    registerInSales: false,
  },
  {
    orderTransactionId: 5,
    extraAmount: 200,
    description: 'Pago en efectivo completo',
    productId: 105,
    productName: 'Tablet Xiaomi Pad 5',
    itemCount: 1,
    methodPayment: MethodPayment.CASH,
    invoiceNumber: 'INV-0005',
    client: 'Fernando Ríos',
    amountPaid: 600,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 300,
    sellingPrice: 400,
    profit: 100,
    operationDate: '2025-09-20',
    registerInSales: false,
  },
  {
    orderTransactionId: 6,
    extraAmount: 0,
    description: 'Compra a crédito',
    productId: 106,
    productName: 'Audífonos Sony WH-1000XM4',
    itemCount: 2,
    methodPayment: MethodPayment.CREDIT_CARD,
    invoiceNumber: 'INV-0006',
    client: 'Iván Morales',
    amountPaid: 1000,
    paymentStatus: PaymentStatus.PENDING,
    deliveryStatus: DeliveryStatus.ON_HOLD,
    purchasePrice: 300,
    sellingPrice: 500,
    profit: 400,
    operationDate: '2025-09-21',
    registerInSales: true,
  },
  {
    orderTransactionId: 7,
    extraAmount: 30,
    description: 'Compra urgente',
    productId: 107,
    productName: 'Disco duro externo 1TB',
    itemCount: 1,
    methodPayment: MethodPayment.DEBIT_CARD,
    invoiceNumber: 'INV-0007',
    client: 'Sandra Vega',
    amountPaid: 130,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.IN_TRANSIT,
    purchasePrice: 70,
    sellingPrice: 100,
    profit: 30,
    operationDate: '2025-09-22',
    registerInSales: true,
  },
  {
    orderTransactionId: 8,
    extraAmount: 10,
    description: 'Accesorios variados',
    productId: 108,
    productName: 'Cables HDMI',
    itemCount: 4,
    methodPayment: MethodPayment.CASH,
    invoiceNumber: 'INV-0008',
    client: 'Erika Sánchez',
    amountPaid: 80,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 10,
    sellingPrice: 20,
    profit: 40,
    operationDate: '2025-09-22',
    registerInSales: false,
  },
  {
    orderTransactionId: 9,
    extraAmount: 0,
    description: 'Pedido en proceso',
    productId: 109,
    productName: 'Smartwatch Huawei GT',
    itemCount: 1,
    methodPayment: MethodPayment.PAYPAL,
    invoiceNumber: 'INV-0009',
    client: 'Luis Pérez',
    amountPaid: 0,
    paymentStatus: PaymentStatus.PENDING,
    deliveryStatus: DeliveryStatus.ON_HOLD,
    purchasePrice: 120,
    sellingPrice: 200,
    profit: 80,
    operationDate: '2025-09-23',
    registerInSales: false,
  },
  {
    orderTransactionId: 10,
    extraAmount: 90,
    description: 'Pago mixto con saldo extra',
    productId: 110,
    productName: 'Router TP-Link AX50',
    itemCount: 1,
    methodPayment: MethodPayment.BANK_TRANSFER,
    invoiceNumber: 'INV-0010',
    client: 'Patricia Gómez',
    amountPaid: 290,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 150,
    sellingPrice: 200,
    profit: 50,
    operationDate: '2025-09-25',
    registerInSales: true,
  },
  // Puedes copiar y adaptar este formato para agregar más registros (11 a 20)

  {
    orderTransactionId: 11,
    extraAmount: 15,
    description: 'Compra en sucursal',
    productId: 111,
    productName: 'Webcam Logitech C920',
    itemCount: 1,
    methodPayment: MethodPayment.DEBIT_CARD,
    invoiceNumber: 'INV-0011',
    client: 'Roberto Díaz',
    amountPaid: 115,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 80,
    sellingPrice: 100,
    profit: 20,
    operationDate: '2025-09-26',
    registerInSales: false,
  },
  {
    orderTransactionId: 12,
    extraAmount: 0,
    description: 'Compra corporativa',
    productId: 112,
    productName: 'Switch de red 8 puertos',
    itemCount: 3,
    methodPayment: MethodPayment.BANK_TRANSFER,
    invoiceNumber: 'INV-0012',
    client: 'Empresa ABC S.A.',
    amountPaid: 450,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 100,
    sellingPrice: 150,
    profit: 150,
    operationDate: '2025-09-26',
    registerInSales: true,
  },
  {
    orderTransactionId: 13,
    extraAmount: 25,
    description: 'Descuento aplicado',
    productId: 113,
    productName: 'Impresora HP Ink Tank',
    itemCount: 1,
    methodPayment: MethodPayment.CREDIT_CARD,
    invoiceNumber: 'INV-0013',
    client: 'Jessica Cruz',
    amountPaid: 375,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 250,
    sellingPrice: 400,
    profit: 150,
    operationDate: '2025-09-27',
    registerInSales: true,
  },
  {
    orderTransactionId: 14,
    extraAmount: 0,
    description: 'Error en entrega',
    productId: 114,
    productName: 'Antena WiFi USB',
    itemCount: 2,
    methodPayment: MethodPayment.PAYPAL,
    invoiceNumber: 'INV-0014',
    client: 'Marco Silva',
    amountPaid: 0,
    paymentStatus: PaymentStatus.INCOMPLETE,
    deliveryStatus: DeliveryStatus.CANCELLED,
    purchasePrice: 20,
    sellingPrice: 40,
    profit: 0,
    operationDate: '2025-09-27',
    registerInSales: false,
  },
  {
    orderTransactionId: 15,
    extraAmount: 100,
    description: 'Oferta relámpago',
    productId: 115,
    productName: 'SSD NVMe 1TB Kingston',
    itemCount: 1,
    methodPayment: MethodPayment.CASH,
    invoiceNumber: 'INV-0015',
    client: 'Andrea Flores',
    amountPaid: 600,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.IN_TRANSIT,
    purchasePrice: 400,
    sellingPrice: 500,
    profit: 100,
    operationDate: '2025-09-28',
    registerInSales: true,
  },

  // Agrega 5 más si los necesitas
  {
    orderTransactionId: 16,
    extraAmount: 0,
    description: 'Pago con transferencia bancaria',
    productId: 116,
    productName: 'Cargador portátil Anker',
    itemCount: 1,
    methodPayment: MethodPayment.BANK_TRANSFER,
    invoiceNumber: 'INV-0016',
    client: 'Oscar Jiménez',
    amountPaid: 180,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 100,
    sellingPrice: 180,
    profit: 80,
    operationDate: '2025-09-28',
    registerInSales: false,
  },
  {
    orderTransactionId: 17,
    extraAmount: 5,
    description: 'Compra parcial',
    productId: 117,
    productName: 'Mousepad XL',
    itemCount: 2,
    methodPayment: MethodPayment.DEBIT_CARD,
    invoiceNumber: 'INV-0017',
    client: 'Luz Marina',
    amountPaid: 60,
    paymentStatus: PaymentStatus.INCOMPLETE,
    deliveryStatus: DeliveryStatus.PENDING,
    purchasePrice: 20,
    sellingPrice: 30,
    profit: 20,
    operationDate: '2025-09-28',
    registerInSales: true,
  },
  {
    orderTransactionId: 18,
    extraAmount: 0,
    description: 'Pedido sin completar',
    productId: 118,
    productName: 'Micrófono Blue Yeti',
    itemCount: 1,
    methodPayment: MethodPayment.PAYPAL,
    invoiceNumber: 'INV-0018',
    client: 'Diego Ramos',
    amountPaid: 0,
    paymentStatus: PaymentStatus.PENDING,
    deliveryStatus: DeliveryStatus.ON_HOLD,
    purchasePrice: 300,
    sellingPrice: 400,
    profit: 100,
    operationDate: '2025-09-29',
    registerInSales: false,
  },
  {
    orderTransactionId: 19,
    extraAmount: 12,
    description: 'Venta por redes sociales',
    productId: 119,
    productName: 'Soporte para laptop',
    itemCount: 1,
    methodPayment: MethodPayment.CREDIT_CARD,
    invoiceNumber: 'INV-0019',
    client: 'Pamela Ruiz',
    amountPaid: 112,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 60,
    sellingPrice: 100,
    profit: 40,
    operationDate: '2025-09-29',
    registerInSales: true,
  },
  {
    orderTransactionId: 20,
    extraAmount: 0,
    description: 'Compra directa en tienda',
    productId: 120,
    productName: 'Base refrigerante para laptop',
    itemCount: 1,
    methodPayment: MethodPayment.CASH,
    invoiceNumber: 'INV-0020',
    client: 'Jorge Estrada',
    amountPaid: 80,
    paymentStatus: PaymentStatus.PAID,
    deliveryStatus: DeliveryStatus.DELIVERED,
    purchasePrice: 40,
    sellingPrice: 80,
    profit: 40,
    operationDate: '2025-09-30',
    registerInSales: false,
  },
];
